add_newline = false

[username]
show_always = true
format = 'â˜ ï¸  [$user]($style) at '

[hostname]
ssh_only = false
format = 'ğŸ–¥ï¸  [$ssh_symbol$hostname]($style) in '

[directory]
truncation_length = 1
format = 'ğŸ“ [$path]($style)[$read_only]($read_only_style) '
